version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs-app
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.crt:/etc/nginx/cert.crt
      - ./nginx/cert.key:/etc/nginx/cert.key
    depends_on:
      - nodejs-app
